### ISSUE TITLE
Are you still developing?

### ISSUE THREAD

**Issue by CaveNightingale** [WoolMC/Wool#21]
I wander if the project is still alive

**Comment by i509VCB** [comment]
This project isn't running anymore but you can go look at https://github.com/FukkitMC which I advise the authors with.

**Comment by CaveNightingale** [comment]
Thanks

**Comment by Devan-Kerman** [comment]
Ok, I nuked the old repo and made a new one with the same stuff because I suck at using github 
https://github.com/FukkitMC/CraftFukkit it is here

**Comment by Devan-Kerman** [comment]
open a new issue there so I can keep track of it

**Comment by CaveNightingale** [comment]
@Devan-Kerman May I have your email address? Discord has been banned in China for several months.

**Comment by Devan-Kerman** [comment]
Yea, devan@cleverpath.com
